version: '3.3'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'rate-limiter'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  cache:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --requirepass password
    volumes:
      - cache:/data

  rate-limiter:
    image: rate-limiter:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      DATABASE_JDBC_URL: 'jdbc:mysql://db:3306/rate-limiter'
      DATABASE_USERNAME: 'user'
      DATABASE_PASSWORD: 'password'
      REDIS_HOST: 'cache'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: 'password'
    depends_on:
      - db
      - cache
    links:
      - db
      - cache

volumes:
  my-db:
  cache:
