version: '3.3'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'rate-limiter'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  cache:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass password
    volumes:
      - cache:/data


volumes:
  my-db:
  cache:
