server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: rate-limiter
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: MYSQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: ${DATABASE_JDBC_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    locations: classpath:db/migration
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}


logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /api-docs

timezone: "UTC"

schedule:
  mysql:
    start: "09:00"
    end: "17:00"
  elastic:
    start: "17:01"
    end: "08:59"

maximum-quota: ${MAXIMUM_QUOTA:5}