server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: service-enrollment
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: MYSQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: ${DATABASE_JDBC_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    locations: classpath:db/migration
    enabled: true

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /api-docs


timezone: "UTC"


